-- ============================================================
-- ASSISTÊNCIA TÉCNICA - SUPABASE
-- Execute no SQL Editor do Supabase
-- ============================================================

create table if not exists public.ordens (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  cliente_nome text not null,
  cliente_documento text,
  cliente_telefone text,

  aparelho_tipo text,
  aparelho_marca text,
  aparelho_modelo text,
  aparelho_serial text,
  aparelho_cor text,
  aparelho_acessorios text,

  defeito_relatado text,
  diagnostico text,

  servico_realizado text,
  pecas_utilizadas text,
  testes_realizados text,

  valor_pecas numeric(12,2) not null default 0,
  valor_mao_obra numeric(12,2) not null default 0,
  desconto numeric(12,2) not null default 0,
  valor_total numeric(12,2) not null default 0,

  garantia text,
  observacoes text,

  status text not null default 'Aberta'
);

alter table public.ordens enable row level security;

drop policy if exists "ordens_select_anon" on public.ordens;
drop policy if exists "ordens_insert_anon" on public.ordens;
drop policy if exists "ordens_update_anon" on public.ordens;
drop policy if exists "ordens_delete_anon" on public.ordens;

create policy "ordens_select_anon"
on public.ordens
for select
to anon
using (true);

create policy "ordens_insert_anon"
on public.ordens
for insert
to anon
with check (true);

create policy "ordens_update_anon"
on public.ordens
for update
to anon
using (true)
with check (true);

create policy "ordens_delete_anon"
on public.ordens
for delete
to anon
using (true);

create index if not exists idx_ordens_status
on public.ordens(status);

create index if not exists idx_ordens_created_at
on public.ordens(created_at desc);

create index if not exists idx_ordens_cliente_nome
on public.ordens(cliente_nome);
